# Generated by Django 4.2.6 on 2024-01-01 11:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Agendamento Ativo')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora_agendamento',
            field=models.TimeField(default=datetime.time(13, 0), verbose_name='Hora do Agendamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='vagas_disponiveis',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('estabelecimento', 'data_agendamento', 'hora_agendamento')},
        ),
        migrations.DeleteModel(
            name='AgendamentoCustomUser',
        ),
        migrations.AddField(
            model_name='agendamentousuario',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.agendamento', verbose_name='Agendamento'),
        ),
        migrations.AddField(
            model_name='agendamentousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='agendamentousuario',
            unique_together={('usuario', 'is_active')},
        ),
    ]
