# Generated by Django 4.2.6 on 2024-01-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0002_agendamentousuario_agendamento_hora_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentousuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Agendamento Ativo'),
        ),
    ]
