# Generated by Django 4.2.6 on 2023-12-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_customuser_teve_covid_ultimos_30_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_apto_agendamento',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
