# Generated by Django 4.2.6 on 2023-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_alter_customuser_is_apto_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_apto_agendamento',
            field=models.BooleanField(default=False, verbose_name='Apto para agendamento'),
        ),
    ]
