# Generated by Django 4.2.6 on 2024-01-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_alter_customuser_cpf_alter_customuser_nome_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(max_length=150, verbose_name='nome completo'),
        ),
    ]
